# Generated by Django 2.2.14 on 2020-09-09 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200906_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedteaminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('ps', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_phone_num', models.IntegerField()),
                ('s1_name', models.CharField(max_length=200)),
                ('s1_email', models.EmailField(max_length=254)),
                ('s1_phone_num', models.IntegerField()),
                ('s1_class', models.IntegerField()),
                ('s1_dob', models.DateField()),
                ('s2_name', models.CharField(max_length=200)),
                ('s2_email', models.EmailField(max_length=254)),
                ('s2_phone_num', models.IntegerField()),
                ('s2_class', models.IntegerField()),
                ('s2_dob', models.DateField()),
                ('s3_name', models.CharField(blank=True, max_length=200)),
                ('s3_email', models.EmailField(max_length=254)),
                ('s3_phone_num', models.IntegerField()),
                ('s3_class', models.IntegerField()),
                ('s3_dob', models.DateField()),
                ('s_gender', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
