# Generated by Django 2.2.14 on 2020-09-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200909_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extendedteaminfo',
        ),
    ]
