# Generated by Django 2.2.14 on 2020-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_extendedteaminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s1_gender',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s2_gender',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s3_gender',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
