# Generated by Django 2.2.14 on 2020-09-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200911_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='num_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
