# Generated by Django 2.2.14 on 2020-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200911_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s1_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s1_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s2_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s2_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s3_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s3_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
