# Generated by Django 2.2.14 on 2020-09-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200911_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s3_phone_num',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
