# Generated by Django 2.2.14 on 2020-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200911_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedteaminfo',
            name='s3_class',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
